modified dev.yml

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -110,10 +110,9 @@ jobs:
       - name: Smoke test
         run: |
           STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://ubu-cicd-development.up.railway.app/health/)
-
-        if [ "$STATUS" = "200" ]; then
-          echo "Smoke test passed!"
-        else
-          echo "Smoke test failed!"
-          exit 1
-        fi
+          if [ "$STATUS" = "200" ]; then
+            echo "Smoke test passed!"
+          else
+            echo "Smoke test failed!"
+            exit 1
+          fi
